### ISSUE TITLE
Feature request: Pony's addressof analogue

### ISSUE THREAD

**Issue by teggotic** [jemc/mare#14]
In pony we have an `addressof` keyword to get the Pointer of the variable. It's mandatory to have such in the Mare to get closer to the C-FFI completeness

**Comment by jemc** [comment]
Can you give me an example of a C function that you tried to call that needed this?

I can use it as a real-world example when I design and implement this feature.

**Comment by teggotic** [comment]
You can look at the [pony-regex](https://github.com/ponylang/regex) example i tried to port to the mare. To be more precise the line is here https://github.com/ponylang/regex/blob/17fcb9c22ab8b7032d3b6e584cc4850ac814717e/regex/regex.pony#L68

**Comment by teggotic** [comment]
@jemc We can do it more Mare-way.
```mare
a U64 = 1
a.address_of // or a.cpointer
```

**Comment by jemc** [comment]
Yeah, that looks nice, and doesn't require any new parser-level keywords.

The only thing I'm unsure about is the fact that this might allow you to carry around a `CPointer(Whatever)` that is no longer valid past the scope of the function where the variable was declared.

Pony prevents this by issuing a compiler error if you try to use `addressof` anywhere but as an argument to an FFI call. However I'm not sure if it's strictly necessary to prevent this because anyone that uses FFI is already breaking safety guarantees, and this is just another safety guarantee broken.

However, I wonder if maybe we could make it an annotation on the `:ffi` function declaration instead. For example:
```mare
:ffi PCRE2
  :fun pcre2_compile_8 (
    buffer CPointer(U8)
    encoding USize
    err CPointer(I32)
    erroffset CPointer(ISize)
	context CPointer(U8)
  ) CPointer(_Pattern)
```

Now, imagine that you tried to call that function with the `err` arg being an `I32` instead of a `CPointer(I32)` as expected. The compiler could be smart enough to know that what you're trying to do is pass the address of that local `I32` variable, and do the right thing with no special syntax on the caller side.

This is kind of nice in that it's all automatic for the caller, and we prevent the caller from being able to "carry around" the address like Pony prevents that - only the C code on the other side can "carry it around".

**Comment by teggotic** [comment]
Im trying to think of another cases, but nothing comes to mind. If it covers everything, then it's better then solution in Pony

**Comment by jemc** [comment]
Spoke with @teggotic about how this could be implemented, and I suggested that the "magic inference" style of working I described above might be too difficult to implement in the `Infer` pass right now due to some recursion issues I am dealing with and trying to resolve in that area of the codebase now.

So I suggested that we amend the plan by adding an `address_of` macro that would mark the places where we want to get the local variable pointer, rather than trying to magically infer that from the FFI call signature.

So the call site would look like this:
```mare
PCRE2.pcre2_compile_8(buffer, encoding, address_of err, address_of erroffset, context)
```
