### ISSUE TITLE
Add early return, break and next

### ISSUE THREAD

**Issue by teggotic** [jemc/mare#29]

**Comment by teggotic** [comment]
What about not allowing early return. We can force users to write more tail-recursive code for example

**Comment by jemc** [comment]
A while ago I kind of had that tendency to reject it, but I used early return a lot in Crystal while building the Mare compiler - it seems too convenient to give up and leave out of the language, even though omitting it might be more easier for the compiler architecture or "more ideologically pure" for the language - I think the convenience is important for the language user, especially because I want Mare to have a focus on productivity.

I have also already agreed to Sean that I will work on this feature soon, because it is a blocker for testing the Mare compiler against Pony-syntax source code. So I'm assigning myself and hope to get to this soon.

**Comment by jemc** [comment]
@teggotic has suggested that he can work on this, so I have taken an initial pass at a design.

The following document describes generally how the features should work, then describes some guidance for how to implement internally in the compiler architecture.

Enjoy the wall of text :smile:

**Comment by jemc** [comment]
# Feature Design

## Early Return

The `return` macro has one optional term, which may be omitted for an implied value of `None`:
```mare
return "example"
return // implicitly, the term is `None`
```

- the value is "caught by" the function body boundary
- if within an `Choice` body, it "jumps away" out of such a block
- if within an `Try` body, it "jumps away" out of such a block
- if within an `Loop` body, it "jumps away" out of such a block
- if within a yield block (`->`), it "jumps away" out of such a block
  - the yielding call will not continue to execute when the yield block jumps away
  - the yielding call must be allowed to finish any needed cleanup operations, such as an outstanding `defer`, or other internal allocations that need deallocating
  - PHASE 1: raise a compiler error if anything the yield block jumps away for any reason - this is not supported yet and will take special, careful codegen to support

## Early Continue

The `continue` macro has one optional term, which may be omitted for an implied value of `None`:
```mare
continue "example"
continue // implicitly, the term is `None`
```

- the value is "caught by" the nearest `Loop` body or `->` block boundary
  - for a `Loop`, the value doesn't matter unless this is the last iteration
  - for a `->` block, the value becomes the "yield in" value passed back to the yielding call
- if not within either of those, a compile error is raised to say it must be within one of those
- if within an `Choice` body, it "jumps away" out of such a block
- if within an `Try` body, it "jumps away" out of such a block
- we do not support early break to some outer block that is not the nearest qualifying block (sometimes called "named" continues) - the author will need to implement such cases in some other way

## Early Break

The `break` macro has one optional term, which may be omitted for an implied value of `None`:
```mare
break "example"
break // implicitly, the term is `None`
```

- the value is "caught by" the nearest `Loop` body or `->` block boundary
  - for a `Loop`, the loop stops and this becomes the result value at the left-hand-side of the loop
  - for a `->` block, the value becomes result value of the yielding call
    - PHASE 1: raise a compiler error for this case - this is not supported yet and will take special, careful codegen to support
    - it does not need to be the subtype of the return type of the yielding function
      - this lets the caller "pull out" any value not expected by the designer of the yielding function
      - it means that the result type of the left side of the call becomes a union of the function's return type and any possible `break` type within the body
    - the yielding call will not continue to execute
    - the yielding call must be allowed to finish any needed cleanup operations, such as an outstanding `defer`, or other internal allocations that need deallocating
- if not within either of those, a compile error is raised to say it must be within one of those
- if within an `Choice` body, it "jumps away" out of such a block
- if within an `Try` body, it "jumps away" out of such a block
- we do not support early break to some outer block that is not the nearest qualifying block (sometimes called "named" breaks) - the author will need to implement such cases in some other way

## Deferred Cleanup

NOTE: this feature is not planned for PHASE 1, but I wanted to start designing it now anyway, since it will complicate how early returns are handled for yield blocks.

The `defer` macro has one (required) term - the expression to defer, which may be a simple term or a parenthesized group:
```mare
defer my_list.clear

defer (
  my_list.each -> (item | env.out.print(Inspect[item]))
  my_list.clear
)
```

- once the `defer` statement is reached, the expression is guaranteed to execute at some point before the function body that contains it gives final control back to the function caller
- if the `defer` statement is not reached in that branch (for example, if an `error!` occurs before reaching the statement), then that defer expression is never "pushed onto the defer queue", and thus it will never execute.
- if multiple defer statements are set up, they are guaranteed to execute in the order in which they were "pushed onto the defer queue" (first in, first out)
- if the deferring function is a yielding function, the associated defers are not executed before each yield - they are only executed on the "final return" of the function
- if the deferring function is a yielding function, the associated defers are guaranteed to execute before final return EVEN IF THE YIELD BLOCK JUMPS AWAY and the rest of the yielding function is not executed
  - from a codegen perspective, this means that if a yielding call is to a function that has defers, we must pass control back to the yielding call's defer section even though we don't pass control back to the normal "continue" function; this is the tricky part.
- PHASE 1: we will not do anything related to `defer` for PHASE 1

# Impact on Compiler Internals

## Overview

Much of the changes involved will be straightforward, now that I have taken the care to detail them here.

The trickiness/uncertainty comes with the `Refer` pass and the `Completeness` pass, which are there to guarantee that local variables and fields don't end up being used before initialization - I'm not 100% sure at this time the best way to refactor those - it will likely take some trial and error before finding the right pattern. They will rely on common analysis stored in the `Jumps::Analysis` to know where a branch may "jump away" and where that jump would be "caught".

Note that this plan only covers the "PHASE 1" of this work, leaving out any work related to yield blocks at this time, because that is likely to be trickier and I want to do a first phase to prove out that this approach is fully feasible before adding all the complexity related to yield blocks.

I have toyed with the idea of refactoring the AST to work only in terms of LLVM-style "Basic Blocks" from the very beginning (starting in the Macros pass where these control flow structures are defined), but I would like to see if we can avoid that for now. It would make the jumping/completeness analysis easier, but would likely make other parts of the code significantly more complicated to compensate. So instead I'd prefer to keep the "intuitive" high-level structures in place if we can, as documented in this proposed design for the internal implementation details:

## AST

- [ ] - Add a new subclass of `AST::Node` called `AST::Jump`
  - contains a `kind` property, which is an enum of `[Error, Return, Continue, Break]`
  - contains a `term` property, of type `Term?`, being `nil` when there is no value term

- [ ] - Refactor all uses/checks for the `AST::Identifier("error!")` to be `AST::Jump` with `kind` of `error`
  - this is the start of supporting jumps, starting with the one kind of jump we already have

## Macros Pass

- [ ] - add `error!` as a macro which converts it from an `Identifier` to a `Jump`
- [ ] - add the `return` macro, which converts to a `Jump`
- [ ] - add the `continue` macro, which converts to a `Jump`
- [ ] - add the `break` macro, which converts to a `Jump`

## Lambda Pass

- Ignore this pass as much as you can for now - I kind of want to get rid of this feature now that we have `->`, and wait for a better design of proper lambdas in the future when we have more concrete use cases for them that are not met by using `->` or by just defining a new type. Just kind of pretend these lambdas don't exist, as much as you can, and just disable them if you find that you must do that in order to get things to compile.

## Classify Pass

- [ ] - Refactor to depend on the `ReferType` pass instead of the `Refer` pass
  - we will be able to easily do this because `Classify` only uses `Refer` in one place to distinguish type identifiers from other identifiers, and this info is gathered first in the `ReferType` pass - no need for any of the further info gathered in the `Refer` pass.
  - we need to do this because the `Jumps` pass depends on `Classify`, and we will need the `Refer` pass to have a dependency on the `Jumps` pass to analyze local variable visibility/completeness in the presence of jumps
  - be sure to update `compiler.cr` with the new dependency list (using `:refer` instead of `:refer_type`), once the code for the pass is using `ReferType::Analysis` instead of `Refer::Analysis`

## Jumps Pass

(Analyzing "jumps away" and "caught by" semantics and storing them for later use)

- [ ] - refactor to detect `error!` as a `AST::Jump` instead of `AST::Identifier`
- [ ] - the `Jumps.away?` analysis should be true for a node if it "jumps away" in EVERY possible branch
  - (currently it only analyzes this for `error!`, but we want it to hold true for all types of `AST::Jump`)
  - "jumps away" means it leaves the block without giving the block a result value - this is distinct from the "caught by" semantics where it jumps TO the block with a value (see the "Feature Design" section above and look at where it is written that the flow "jumps away")
- [ ] - similarly, the `Jumps.away_possibly?` analysis should be true for a node if it "jumps away" in ANY possible branch
- [ ] - add a new property to the `Jumps::Analysis` called "catches" (`{} of AST::Node => Array(AST::Jump)`
- [ ] - whenever encountering a `AST::Jump::Break` or `AST::Jump::Continue`, assign that to the "catches" list of the nearest `AST::Loop` node
- [ ] - whenever encountering a `AST::Jump::Error`, assign that to the "catches" list of the nearest `AST::Try` that contains it, if any (don't assign it to any list if the error jumps away from the whole function without being caught)
- [ ] - whenever encountering a `AST::Jump::Return`, assign that to the "catches" list of the overall `AST::Group` that contains the whole function body
- [ ] - track the state for the nearest function body, loop, and yield block
- [ ] - PHASE 1: raise a compiler error if any kind of jump appears uncaught within a yield block - we won't support this until a later phase of work, after we've proven that this phase is working how we want it to

## Refer

(Analyzing local variable definition sites)

- [ ] - Remove the `Refer::RaiseError` type because we no longer treat an `error!` as an identifier, so no need to resolve it in the `Refer::Analysis`
  - will also need to refactor downstream code that checks for/uses this type
- [ ] - Refactor to use the `Jumps::Analysis` to know when a branch might jump away before defining a variable, but be caught before we try to use the variable - basically trying to detect if there is some branch of execution in which the variable may not be defined
  - I don't have specific guidance for you at this time - this is likely to be rather tricky and subtle, so take your time, and write lots of test case examples in the specs.

## Infer::Info

(Defining the appropriate `Infer::Info` classes)

- [ ] - Make a subclass of `Infer::Info` for each kind of `AST::Jump` - don't worry about trying to collapse into one single `Infer::Jump` class for now - we can always collapse it later if it makes sense, but at the start I want to assume we will need separate code for each one until we are sure of otherwise.
  - Copy code from `Infer::Sequence` as a baseline for how to wire up the tethers/downstreams based on inner term's `Infer::Info` (referencing how it uses its `final_term` property)
  - Copy the `resolve!` from `Infer::RaiseError` as a baseline for how to return the "unsatisfiable" type - the left side of any Jump has no satisifiable type for it, because any code that tries to get the direct value of it would be unreachable - it would jump away before reaching that code.
- [ ] - Make `Infer::Phi` an `abstract class` and make subclasses called `Infer::Choice` and `Infer::Loop`.
- [ ] - `Infer::Loop` should have two new properties to tracks the list of infos for the early continues and early breaks that occur within it.
- [ ] - `Infer::FuncBody` should have a new property to track the list of infos for the early returns that occur within it
- The `Infer::Loop#initialize` method should call `add_downstream` on each of its child jumps, which will assign itself as constraining the type of those jump nodes.
- When creating an `Infer::FuncBody`, use the `Jumps::Analysis` to get the `Infer::Info` for each possible jump that may be caught by the loop, and pass it to the early returns list (raising a `NotImplementedError` if it is the wrong kind of jump to be caught by a loop).
- The `Infer::FuncBody#initialize` method should call `add_downstream` on each of its child jumps, which will assign itself as constraining the type of those jump nodes.

## PreInfer Pass

(Constructing the appropriate `Infer::Info` tree)

- When encountering an `AST::Jump`, make the appropriate class of `Infer::Info` created to represent that jump.
- When creating an `Infer::Loop` (previously `Infer::Phi`), use the `Jumps::Analysis` to get the `Infer::Info` for each possible jump that may be caught by the loop, and pass it to the early continues or early breaks list within the `Infer::Loop` node, as appropriate (raising a `NotImplementedError` if it is the wrong kind of jump to be caught by a loop).

## Completeness Pass

(Confirming that a constructor initializes all of its fields)

- [ ] - Like the `Refer` pass, this will need to be refactored to use the `Jumps::Analysis` to account for jumps that may make some branches get skipped that otherwise would initialize a field.
  - I don't have specific guidance for you at this time - this is likely to be rather tricky and subtle, so take your time, and write lots of test case examples in the specs.

## CodeGen Pass

(Generating code that can do jumps)

- [ ] - Refactor `Refer::RaiseError` for an `AST::Identifier` to instead handle the case of an `AST::Jump` of kind `Error`
- [ ] - When encountering an `AST::Jump::Return`, use the appropriate approach based on the calling convention of the function (retrieved using `func_frame.gfunc.not_nil!.calling_convention(ctx)`):
  - `:constructor_cc` - use `@builder.ret` with no value
  - `:simple_cc` - use `@builder.ret` with `gen_assign_cast` for the value
  - `:error_cc` - use `gen_return_using_error_cc`
  - `:yield_cc`, `:yield_error_cc` - use `gen_final_return_using_yield_cc`
- [ ] - Similar to the `@try_else_stack`, we will want to introduce a few new properties (`loop_continue_stack`, `loop_break_stack`) which can be used to grab the `LLVM::BasicBlock` to jump to when encountering an `AST::Jump::Continue` or `AST::Jump::Break`.
- [ ] - In `gen_loop`, we need to push onto that stack at the start, and pop off at the end, generating code that appropriately handles the `continue` or `break` in each of those associated loops (see `gen_try` for an example of how this works for that)
- PHASE 1 - for anything related to yield blocks that is not straightforward, leave it out with a `NotImplementedError` and we can discuss how to approach in phase 2

**Comment by jemc** [comment]
I think we need a better plan than the Jumps analysis we have discussed above.

Let's not continue working on this until the following ticket is ready: https://github.com/jemc/mare/issues/75

Marking this ticket as blocked.

**Comment by jemc** [comment]
I've decided that I prefer the word `next` over `continue`, so I'm editing the ticket title and design comments above to specify `next` instead of `continue` as the macro name.

**Comment by jemc** [comment]
I've finished the blocking ticket (#75) and have renamed `continue` as `next`, and I will now be working on finishing up this ticket, including a bunch of tests in the language semantics tests directory, and any changes needed to bring the actual behavior in line with those tests.
