### ISSUE TITLE
try keyword resolving error

### ISSUE THREAD

**Issue by teggotic** [jemc/mare#32]
```mare
:actor Main
  :new (env Env)
    str = "10231"

    t = try(
      str.parse_i64!
    )
```
![image](https://user-images.githubusercontent.com/16068886/87605781-20a88b00-c702-11ea-9943-cd90dd760878.png)

**Comment by jemc** [comment]
This happens because you're missing the mandatory whitespace following the `try`. Without that whitespace, this looks like a function call to the parser.

**Comment by teggotic** [comment]
You mean I can have a function called try?

**Comment by jemc** [comment]
Yeah, you can have a local variable called `try`, a property called `try`, or a function called `try`.

Mare doesn't really have any "reserved words" that are separated at the parser level - everything that is reserved is a symbol, but words are all fair game for use wherever you want.

The control flow statement words (`if`, `try`, `while`, etc) are all part of the "macros" system, which basically means that they are applied later in the compilation process, and are only picked up if you use them in a particular context (usually at the start of some whitespace-separated expressions). It is my goal to make it so that the user can define custom macros that have syntax just like the control flow keywords, but do custom things. As a result, we can't use reserved words in the parser because we wouldn't know what words to reserve for the user macros. That custom macros system is not in place yet, but everything in the compiler and parser is set up to be compatible with that later.

After I merge your PR about control flow statements (#33) I will spend some time explaining these ideas a bit more in that document to hopefully make this clearer to you and to others.

**Comment by teggotic** [comment]
That sound cool very cool. Closing this one
