### ISSUE TITLE
remove crystal libs from repo

### ISSUE THREAD

**Issue by teggotic** [jemc/mare#43]

**Comment by jemc** [comment]
I think the reason I included them here was so that it would be easy for anyone to clone this repo and build/test/work with the docker workflow without having any `crystal` tooling on their machine.

So it should be fine to remove, so long as the `Makefile`'s `make ready` task knows how to pull the libraries into the container according to the `shard.lock` - so that we still are meeting the requirement of not requiring crystal/shard tooling outside of the container on the host machine.

**Comment by jemc** [comment]
I don't think there's much value removing them from the repo, so I'm closing this ticket for now.

If someone wants to pursue this idea with a justification, I can re-open.
