### ISSUE TITLE
Add not_none! function to remove None from union type

### ISSUE THREAD

**Issue by teggotic** [jemc/mare#56]

**Comment by jemc** [comment]
Yeah, as we discussed I think we need the equivalent of Crystal's `not_nil!`.

But I'm trying to think if there's a better way to name this, because `not_none!`, while it makes the point, kind of reads awkwardly, due to it being sort of like a double negative, which is generally frowned upon in English.

I'm trying to think if there is some "positive" way to express this rather than the double negative, while still meeting the following requirements:
- is not ambiguous - it should be clear what it means
- is not technically incorrect
- is fairly short and succinct, since this may be used a lot
- does not "take away" a method name that someone might conceivably want to use for some other purpose, since it will be impossible to override this pseudo-method, just like as

**Comment by jemc** [comment]
One option that comes to mind to make this more general would be to introduce `not!`, which takes a type argument and does the opposite of what `as!` does. That would make the "not None" use case be written as `maybe_thing.not!(None)`.

This has the advantage of being flexible, because you could use it for other types besides `None` (some generic classes in Pony use a custom private `_None` to ensure that `None` can be a valid part of the normal value's type argument, without breaking the internal logic.

It is unambiguous, technically correct, succinct, and hopefully isn't a name that people will have wanted to use for their own method.
